name: 'Mirror to eu.org'
on:
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - run: |
          rm .github/workflows/mirror-to-euorg.yml
          echo "blog.lyniko.eu.org" > CNAME
          git config user.name github-actions-sync
          git config user.email github-actions-sync@github.com
          git add .
          git commit --amend --no-edit
          git remote set-url origin https://github.com/Young-Lord-Blogs/Blog-eu.org
          git push -f
